### ISSUE TITLE
Add support for ssl, ssl_verify fields in "ircb networks create" command

### ISSUE THREAD

**Issue by rtnpro** [waartaa/ircb#22]
TODO:
- update signature: https://github.com/waartaa/ircb/blob/develop/ircb/stores/network.py#L34
- update call to Network:  https://github.com/waartaa/ircb/blob/develop/ircb/stores/network.py#L39
- Add CLI option for `ssl`: default=False, `ssl_verify`: default="CERT_NONE" at https://github.com/waartaa/ircb/blob/develop/ircb/cli/network.py#L22 and update call at: https://github.com/waartaa/ircb/blob/develop/ircb/cli/network.py#L27

**Comment by rtnpro** [comment]
@PolBaladas Task for you.

**Comment by PolBaladas** [comment]
Nice!

**Comment by PolBaladas** [comment]
Created a PR :top:

**Comment by PolBaladas** [comment]
I've seen you merged the PR, should we close this issue? what's next? :+1: 
i like this project hehe :smile:

**Comment by rtnpro** [comment]
On Dec 12, 2015 7:10 PM, "Pol Baladas Luna" notifications@github.com
wrote:

> I've seen you merged the PR, should we close this issue? what's next?
> i like this project hehe

Good to hear that. Hey, I was away from keyboard for most of the day today.
I will be around on IRC tomorrow. So, feel free to ping me.

**Comment by rtnpro** [comment]
Fixed!
