### ISSUE TITLE
Add a logging framework

### ISSUE THREAD

**Issue by sayanchowdhury** [waartaa/ircb#43]

**Comment by slick666** [comment]
+1

**Comment by slick666** [comment]
@sayanchowdhury we should probably add a "feature" flag to this and a milestone if possible.

It looks like we already have some logging defined in the config.py. While we have each one named explicitly I think we could move to using the module hierarchy to accomplish the same thing. This is that `logging.getLogger(__name__)` pattern. Everything would roll up to the root and by default would be logged to the console. If someone wanted to take the stores for example. They could define that handler and either propagate that up (default) or isolate the logging to that particular method.

Does this make sense? what are your thoughts on this?

**Comment by sayanchowdhury** [comment]
I was actually planning on the same lines. My plan was to place the loading of config into the base command so that it's available as soon as we hit any command and then have a common handler `ircb`.for logging

**Comment by slick666** [comment]
@sayanchowdhury, I'll knock out a first draft of that as soon as I can and we can go from there.

**Comment by sayanchowdhury** [comment]
@slick666 So, I have pushed a `load_config` [function](https://git.io/vwmS8) here which is called [here](https://git.io/vwmSq). Comments?

/cc @rtnpro
