### ISSUE TITLE
python.h directory is not there

### ISSUE THREAD

**Issue by madanmohana** [waartaa/ircb#44]
bcrypt/bcrypt_python.c:18:20: fatal error: Python.h: No such file or directory
 #include "Python.h"

**Comment by pypingou** [comment]
Are you missing python-devel?

This ticket misses quite a bit of context. How did you encounter this error? Are you installing bcrypt by pip? System wide? In a virtual environment? Which OS do you run? Which version?

**Comment by madanmohana** [comment]
encounter this error while running setup.py in ubuntu on terminal-- "python
setup.py develop"

**Comment by pypingou** [comment]
so it looks like it's trying to install bcrypt locally by fails because of the missing header for python.

I think on ubuntu the package is named python-dev

**Comment by madanmohana** [comment]
thank you very much

**Comment by pypingou** [comment]
Does that mean that it works and solved the problem for you?

**Comment by pypingou** [comment]
Does that mean that it works and solved the problem for you?

**Comment by pypingou** [comment]
Does that mean that it works and solved the problem for you?

**Comment by slick666** [comment]
@pypingou can we close this one?

**Comment by pypingou** [comment]
@slick666 well, @madanmohana never replied but I'm going to close it yes.

It can always be reopened if needed.
