### ISSUE TITLE
/.meteor/meteor' is not executable.

### ISSUE THREAD

**Issue by madanmohana** [waartaa/ircb#45]
root@deepak-K56CA:~/waartaa/app# meteor
'/home/deepak/.meteor' exists, but '/home/deepak/.meteor/meteor' is not executable.

Remove it and try again.

**Comment by rtnpro** [comment]
How did you get this error? And `ircb` is not a meteor app.

**Comment by madanmohana** [comment]
while executing 
git clone git://github.com/meteor/meteor.git

**Comment by sayanchowdhury** [comment]
Closing this issue as this is related to `waartaa` and not `ircb`

**Comment by stvenyin** [comment]
'/home/metaor/.meteor' exists, but '/home/metaor/.meteor/meteor' is not executable.

**Comment by bbachi** [comment]
did anybody find the solution for this??
