### ISSUE TITLE
not able to connect python to mysql

### ISSUE THREAD

**Issue by madanmohana** [waartaa/ircb#46]
> > > import MySQLdb
> > > db=MySQLdb.connect(host="localhost",user="deepak",passwd="",db="hanuman")
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "/usr/lib/python2.7/dist-packages/MySQLdb/**init**.py", line 81, in Connect
> > >     return Connection(_args, *_kwargs)
> > >   File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 187, in **init**
> > >     super(Connection, self).**init**(_args, *_kwargs2)
> > > _mysql_exceptions.OperationalError: (1045, "Access denied for user 'deepak'@'localhost' (using password: NO)")

**Comment by pypingou** [comment]
> "Access denied for user 'deepak'@'localhost' 

That looks like a configuration problem, nothing related to `ircb`

**Comment by sayanchowdhury** [comment]
Closing this issue as this is not related to `ircb`
