### ISSUE TITLE
Invalid SSL Certificates

### ISSUE THREAD

**Issue by maxking** [waartaa/ircb#93]
The Readme for the project says:
```
IRC client should have the following settings enabled:

    Use SSL for all server on this network
    Accept invalid SSL certificate
```

I am wondering what is the exact limitation in the project that needs 2nd setting to be enabled? Is it because ircb uses self generated & signed messages or something else?

**Comment by rtnpro** [comment]
On Wed, Feb 22, 2017 at 4:22 AM, Abhilash Raj <notifications@github.com> wrote:
> The Readme for the project says:
>
> IRC client should have the following settings enabled:
>
>     Use SSL for all server on this network
>     Accept invalid SSL certificate
>
> I am wondering what is the exact limitation in the project that needs 2nd
> setting to be enabled?

>Is it because ircb uses self generated & signed
> messages or something else?
Yes!

**Comment by maxking** [comment]
Thanks!
